// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: order_management.proto

package ecommerce

import (
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumTest_State int32

const (
	EnumTest_UNKNOWN EnumTest_State = 0
	EnumTest_RUNNING EnumTest_State = 1
)

// Enum value maps for EnumTest_State.
var (
	EnumTest_State_name = map[int32]string{
		0: "UNKNOWN",
		1: "RUNNING",
	}
	EnumTest_State_value = map[string]int32{
		"UNKNOWN": 0,
		"RUNNING": 1,
	}
)

func (x EnumTest_State) Enum() *EnumTest_State {
	p := new(EnumTest_State)
	*p = x
	return p
}

func (x EnumTest_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumTest_State) Descriptor() protoreflect.EnumDescriptor {
	return file_order_management_proto_enumTypes[0].Descriptor()
}

func (EnumTest_State) Type() protoreflect.EnumType {
	return &file_order_management_proto_enumTypes[0]
}

func (x EnumTest_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumTest_State.Descriptor instead.
func (EnumTest_State) EnumDescriptor() ([]byte, []int) {
	return file_order_management_proto_rawDescGZIP(), []int{3, 0}
}

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Items       []string `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Description string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price       float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Destination string   `protobuf:"bytes,5,opt,name=destination,proto3" json:"destination,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_management_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_management_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_management_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Order) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Order) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type Outer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inner []*Outer_Inner `protobuf:"bytes,1,rep,name=inner,proto3" json:"inner,omitempty"`
}

func (x *Outer) Reset() {
	*x = Outer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_management_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Outer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer) ProtoMessage() {}

func (x *Outer) ProtoReflect() protoreflect.Message {
	mi := &file_order_management_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer.ProtoReflect.Descriptor instead.
func (*Outer) Descriptor() ([]byte, []int) {
	return file_order_management_proto_rawDescGZIP(), []int{1}
}

func (x *Outer) GetInner() []*Outer_Inner {
	if x != nil {
		return x.Inner
	}
	return nil
}

type OuterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *OuterResponse) Reset() {
	*x = OuterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_management_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OuterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OuterResponse) ProtoMessage() {}

func (x *OuterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_management_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OuterResponse.ProtoReflect.Descriptor instead.
func (*OuterResponse) Descriptor() ([]byte, []int) {
	return file_order_management_proto_rawDescGZIP(), []int{2}
}

func (x *OuterResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type EnumTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State EnumTest_State `protobuf:"varint,1,opt,name=state,proto3,enum=ecommerce.EnumTest_State" json:"state,omitempty"`
}

func (x *EnumTest) Reset() {
	*x = EnumTest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_management_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnumTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumTest) ProtoMessage() {}

func (x *EnumTest) ProtoReflect() protoreflect.Message {
	mi := &file_order_management_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumTest.ProtoReflect.Descriptor instead.
func (*EnumTest) Descriptor() ([]byte, []int) {
	return file_order_management_proto_rawDescGZIP(), []int{3}
}

func (x *EnumTest) GetState() EnumTest_State {
	if x != nil {
		return x.State
	}
	return EnumTest_UNKNOWN
}

type OneofTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*OneofTest_Id
	//	*OneofTest_Name
	Type isOneofTest_Type `protobuf_oneof:"type"`
}

func (x *OneofTest) Reset() {
	*x = OneofTest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_management_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneofTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofTest) ProtoMessage() {}

func (x *OneofTest) ProtoReflect() protoreflect.Message {
	mi := &file_order_management_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofTest.ProtoReflect.Descriptor instead.
func (*OneofTest) Descriptor() ([]byte, []int) {
	return file_order_management_proto_rawDescGZIP(), []int{4}
}

func (m *OneofTest) GetType() isOneofTest_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *OneofTest) GetId() int32 {
	if x, ok := x.GetType().(*OneofTest_Id); ok {
		return x.Id
	}
	return 0
}

func (x *OneofTest) GetName() string {
	if x, ok := x.GetType().(*OneofTest_Name); ok {
		return x.Name
	}
	return ""
}

type isOneofTest_Type interface {
	isOneofTest_Type()
}

type OneofTest_Id struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type OneofTest_Name struct {
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

func (*OneofTest_Id) isOneofTest_Type() {}

func (*OneofTest_Name) isOneofTest_Type() {}

type ProtoTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Is  bool  `protobuf:"varint,1,opt,name=is,proto3" json:"is,omitempty"`
	Num int32 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	// Types that are assignable to Type:
	//	*ProtoTest_Id
	//	*ProtoTest_Name
	Type isProtoTest_Type `protobuf_oneof:"type"`
}

func (x *ProtoTest) Reset() {
	*x = ProtoTest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_management_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoTest) ProtoMessage() {}

func (x *ProtoTest) ProtoReflect() protoreflect.Message {
	mi := &file_order_management_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoTest.ProtoReflect.Descriptor instead.
func (*ProtoTest) Descriptor() ([]byte, []int) {
	return file_order_management_proto_rawDescGZIP(), []int{5}
}

func (x *ProtoTest) GetIs() bool {
	if x != nil {
		return x.Is
	}
	return false
}

func (x *ProtoTest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (m *ProtoTest) GetType() isProtoTest_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *ProtoTest) GetId() int32 {
	if x, ok := x.GetType().(*ProtoTest_Id); ok {
		return x.Id
	}
	return 0
}

func (x *ProtoTest) GetName() string {
	if x, ok := x.GetType().(*ProtoTest_Name); ok {
		return x.Name
	}
	return ""
}

type isProtoTest_Type interface {
	isProtoTest_Type()
}

type ProtoTest_Id struct {
	Id int32 `protobuf:"varint,3,opt,name=id,proto3,oneof"`
}

type ProtoTest_Name struct {
	Name string `protobuf:"bytes,4,opt,name=name,proto3,oneof"`
}

func (*ProtoTest_Id) isProtoTest_Type() {}

func (*ProtoTest_Name) isProtoTest_Type() {}

type RepeatTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
}

func (x *RepeatTest) Reset() {
	*x = RepeatTest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_management_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatTest) ProtoMessage() {}

func (x *RepeatTest) ProtoReflect() protoreflect.Message {
	mi := &file_order_management_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatTest.ProtoReflect.Descriptor instead.
func (*RepeatTest) Descriptor() ([]byte, []int) {
	return file_order_management_proto_rawDescGZIP(), []int{6}
}

func (x *RepeatTest) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

type Outer_Inner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Outer_Inner) Reset() {
	*x = Outer_Inner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_management_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Outer_Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer_Inner) ProtoMessage() {}

func (x *Outer_Inner) ProtoReflect() protoreflect.Message {
	mi := &file_order_management_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer_Inner.ProtoReflect.Descriptor instead.
func (*Outer_Inner) Descriptor() ([]byte, []int) {
	return file_order_management_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Outer_Inner) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_order_management_proto protoreflect.FileDescriptor

var file_order_management_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x72, 0x63, 0x65, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x87, 0x01, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x58, 0x0a,
	0x05, 0x4f, 0x75, 0x74, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63,
	0x65, 0x2e, 0x4f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x05, 0x69,
	0x6e, 0x6e, 0x65, 0x72, 0x1a, 0x21, 0x0a, 0x05, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x28, 0x0a, 0x0e, 0x4f, 0x75, 0x74, 0x65, 0x72,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x5e, 0x0a, 0x08, 0x45, 0x6e, 0x75, 0x6d, 0x54, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x65,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x54, 0x65, 0x73,
	0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x21,
	0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10,
	0x01, 0x22, 0x3b, 0x0a, 0x09, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x54, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x5d,
	0x0a, 0x09, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x54, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x69, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6e,
	0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x10, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x20, 0x0a,
	0x0a, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x54, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32,
	0x82, 0x03, 0x0a, 0x0f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x3a, 0x0a, 0x08, 0x67, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12,
	0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x10, 0x2e,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12,
	0x3a, 0x0a, 0x08, 0x61, 0x64, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x10, 0x2e, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x1a, 0x1c, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x40, 0x0a, 0x0c, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x1c, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x10, 0x2e, 0x65, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x30, 0x01, 0x12, 0x40, 0x0a,
	0x0c, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x10, 0x2e,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x1a,
	0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x28, 0x01, 0x12,
	0x35, 0x0a, 0x06, 0x75, 0x70, 0x54, 0x65, 0x73, 0x74, 0x12, 0x10, 0x2e, 0x65, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x4f, 0x75, 0x74, 0x65, 0x72, 0x1a, 0x19, 0x2e, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x4f, 0x75, 0x74, 0x65, 0x72, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x08, 0x65, 0x6e, 0x75, 0x6d, 0x54, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a,
	0x13, 0x2e, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2e, 0x45, 0x6e, 0x75, 0x6d,
	0x54, 0x65, 0x73, 0x74, 0x42, 0x11, 0x5a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_order_management_proto_rawDescOnce sync.Once
	file_order_management_proto_rawDescData = file_order_management_proto_rawDesc
)

func file_order_management_proto_rawDescGZIP() []byte {
	file_order_management_proto_rawDescOnce.Do(func() {
		file_order_management_proto_rawDescData = protoimpl.X.CompressGZIP(file_order_management_proto_rawDescData)
	})
	return file_order_management_proto_rawDescData
}

var file_order_management_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_order_management_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_order_management_proto_goTypes = []interface{}{
	(EnumTest_State)(0),          // 0: ecommerce.EnumTest.State
	(*Order)(nil),                // 1: ecommerce.Order
	(*Outer)(nil),                // 2: ecommerce.Outer
	(*OuterResponse)(nil),        // 3: ecommerce.Outer_response
	(*EnumTest)(nil),             // 4: ecommerce.EnumTest
	(*OneofTest)(nil),            // 5: ecommerce.OneofTest
	(*ProtoTest)(nil),            // 6: ecommerce.ProtoTest
	(*RepeatTest)(nil),           // 7: ecommerce.RepeatTest
	(*Outer_Inner)(nil),          // 8: ecommerce.Outer.Inner
	(*wrappers.StringValue)(nil), // 9: google.protobuf.StringValue
	(*wrappers.Int32Value)(nil),  // 10: google.protobuf.Int32Value
}
var file_order_management_proto_depIdxs = []int32{
	8,  // 0: ecommerce.Outer.inner:type_name -> ecommerce.Outer.Inner
	0,  // 1: ecommerce.EnumTest.state:type_name -> ecommerce.EnumTest.State
	9,  // 2: ecommerce.OrderManagement.getOrder:input_type -> google.protobuf.StringValue
	1,  // 3: ecommerce.OrderManagement.addOrder:input_type -> ecommerce.Order
	9,  // 4: ecommerce.OrderManagement.searchOrders:input_type -> google.protobuf.StringValue
	1,  // 5: ecommerce.OrderManagement.updateOrders:input_type -> ecommerce.Order
	2,  // 6: ecommerce.OrderManagement.upTest:input_type -> ecommerce.Outer
	10, // 7: ecommerce.OrderManagement.enumTest:input_type -> google.protobuf.Int32Value
	1,  // 8: ecommerce.OrderManagement.getOrder:output_type -> ecommerce.Order
	9,  // 9: ecommerce.OrderManagement.addOrder:output_type -> google.protobuf.StringValue
	1,  // 10: ecommerce.OrderManagement.searchOrders:output_type -> ecommerce.Order
	9,  // 11: ecommerce.OrderManagement.updateOrders:output_type -> google.protobuf.StringValue
	3,  // 12: ecommerce.OrderManagement.upTest:output_type -> ecommerce.Outer_response
	4,  // 13: ecommerce.OrderManagement.enumTest:output_type -> ecommerce.EnumTest
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_order_management_proto_init() }
func file_order_management_proto_init() {
	if File_order_management_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_order_management_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_management_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Outer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_management_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OuterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_management_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnumTest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_management_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneofTest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_management_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoTest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_management_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatTest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_management_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Outer_Inner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_order_management_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*OneofTest_Id)(nil),
		(*OneofTest_Name)(nil),
	}
	file_order_management_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*ProtoTest_Id)(nil),
		(*ProtoTest_Name)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_order_management_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_management_proto_goTypes,
		DependencyIndexes: file_order_management_proto_depIdxs,
		EnumInfos:         file_order_management_proto_enumTypes,
		MessageInfos:      file_order_management_proto_msgTypes,
	}.Build()
	File_order_management_proto = out.File
	file_order_management_proto_rawDesc = nil
	file_order_management_proto_goTypes = nil
	file_order_management_proto_depIdxs = nil
}
